Lab1/Lab1/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('articles.urls'))
]

Lab1/articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'
urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create_article, name='create_article'),
    path('edit/<int:article_id>/', views.edit_article, name='edit_article'),
    path('delete/<int:article_id>/', views.remove_article, name='remove_article'),
    path('logout/', views.logout_user, name='logout'),
    path('register/', views.register, name='register'),
    path('login/', views.user_login, name='login')
]

Lab1/articles/models.py
from django.db import models


class Article(models.Model):
    title = models.CharField(max_length=100)
    text = models.TextField()
    publish_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

Lab1/articles/forms.py
from articles.models import Article
from django import forms


class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ['title', 'text']

Lab1/articles/views.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404

from articles.forms import ArticleForm
from articles.models import Article


@login_required
def index(request):
    articles = Article.objects.order_by('-publish_date').all()

    return render(request, 'articles/index.html', {'articles': articles})


@login_required
def create_article(request):
    form = ArticleForm(request.POST or None)
    if request.method == 'POST' and form.is_valid():
        form.save()
        return redirect('articles:index')
    return render(request, 'articles/article_form.html', {'form': form})


@login_required
def edit_article(request, article_id):
    article = get_object_or_404(Article, id=article_id)
    form = ArticleForm(request.POST or None, instance=article)
    if request.method == 'POST' and form.is_valid():
        form.save()
        return redirect('articles:index')
    return render(request, 'articles/article_form.html', {'form': form})


@login_required
def remove_article(request, article_id):
    article = get_object_or_404(Article, id=article_id)
    if request.method == 'POST':
        article.delete()
        return redirect('articles:index')
    return render(request, 'articles/remove_article.html', {"article": article})


def logout_user(request):
    logout(request)
    return redirect('articles:login')


def register(request):
    form = UserCreationForm(request.POST or None)
    if request.method == 'POST' and form.is_valid():
        form.save()
        username = form.cleaned_data.get('username')
        raw_password = form.cleaned_data.get('password1')
        user = authenticate(username=username, password=raw_password)
        login(request, user)
        return redirect('articles:index')
    return render(request, 'auth/register.html', {'form': form})


def user_login(request):
    form = AuthenticationForm(request, data=request.POST or None)
    if request.method == 'POST' and form.is_valid():
        user = authenticate(**form.cleaned_data)
        if user is not None:
            login(request, user)
            return redirect('articles:index')
    return render(request, 'auth/login.html', {'form': form})

Lab1/articles/templates/articles/article_form.html
{% extends 'base.html' %}

{% block content %}
    <h1 class="article-heading">Add Article</h1>
    <form class="article-form" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="submit-button save-article" type="submit">Save</button>
    </form>
{% endblock %}

Lab1/articles/templates/articles/article_item.html
<li>
    <div class="article-header">
        <time>{{ article.publish_date|date:"d.m.Y" }}</time>
        <h3>{{ article.title }}</h3>

        <div>
            <a class="edit-article-link" href="{% url 'articles:edit_article' article.id %}">Edit</a>
            <a class="remove-article-link" href="{% url 'articles:remove_article' article.id %}">Remove</a>
        </div>
    </div>
    <p>{{ article.text }}</p>
</li>

Lab1/articles/templates/articles/index.html
{% extends 'base.html' %}

{% block content %}
    <a href="{% url 'articles:create_article' %}" class="create-article-link">
        Create Article
    </a>

    {% if articles %}
        <ul class="article-list">
            {% for article in articles %}
                {% include 'articles/article_item.html' with article=article %}
            {% endfor %}
        </ul>
    {% else %}
        <p class="no-articles-message">No articles yet!</p>
    {% endif %}

{% endblock %}

Lab1/articles/templates/articles/remove_article.html
{% extends 'base.html' %}

{% block content %}
    <div class="delete-article-container">
        <h1 class="delete-article-heading">Delete Article</h1>

        <p class="delete-confirmation-text">Are you sure you want to delete "{{ article.title }}"?</p>

        <form method="POST">
            {% csrf_token %}
            <a href="{% url 'articles:index' %}" class="cancel-button">Cancel</a>
            <button type="submit" class="delete-article-button">Delete</button>
        </form>
    </div>
{% endblock %}

Lab1/articles/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Lab 1</title>
    <link href="{% static 'styles.css' %}" rel="stylesheet">
</head>
<body>
    {% if request.user.is_authenticated %}
        <header>
            <a class="logout-link" href="{% url 'articles:logout' %}">Logout</a>
        </header>
    {% endif %}

    {% block content %}
        <h1>Hello World!</h1>
    {% endblock %}
</body>
</html>

Lab1/articles/templates/index.html
{% extends 'base.html' %}

{% block content %}
    <h1>Articles:</h1>

    <a href="{% url 'articles:create_article' %}">
        Create Article
    </a>

    {% if articles %}
        <ul>
            {% for article in articles %}
                {% include 'article_item.html' with article=article %}
            {% endfor %}
        </ul>
    {% else %}
        <p>No articles yet!</p>
    {% endif %}

{% endblock %}

Lab1/articles/templates/input-field.html
<div class="input-field">
    {{ field.label_tag }}
    {{ field }}
    {% for error in field.errors %}
        <p class="input-error">{{ error }}</p>
    {% endfor %}
</div>

Lab1/articles/templates/remove_article.html
{% extends 'base.html' %}

{% block content %}
    <h1>Delete Article</h1>

    <p>Are you sure you want to delete "{{ article.title }}"?</p>

    <form method="post">
        {% csrf_token %}
        <a href="{% url 'articles:index' %}">Cancel</a>
        <button type="submit">Delete</button>
    </form>
{% endblock %}